/**
 * 压缩章句数据 → src/data/versesData.compressed.ts（运行时解压，控制分包体积）
 *
 * 背景：2026-08-13 注释升级后 20 个篇章文件共 ~1.5MB TS，构建出的分包 sub-vendors.js
 * 达 2.86MB，超出微信单个分包 2M 上限。此脚本将全部章句序列化为 JSON 后
 * deflateRaw + base64，运行时由 src/utils/inflate.ts 解压，分包可降到 ~0.7MB。
 *
 * 数据格式：base64( deflateRaw( utf8( JSON.stringify({ verses: Verse[] }) ) ) )
 * 生成的 versesData.compressed.ts 提交到 git；数据变更后需重跑本脚本
 * （tests/versesDataCompressed.test.ts 的一致性用例会拦截"改了数据忘了生成"）。
 *
 * 运行：node scripts/compress_verses.cjs（或 npm run data:compress）
 */
const fs = require('fs');
const path = require('path');
const zlib = require('zlib');
const ts = require('typescript');

const ROOT = path.join(__dirname, '..');
const VERSES_DIR = path.join(ROOT, 'src', 'data', 'verses');
const OUT_FILE = path.join(ROOT, 'src', 'data', 'versesData.compressed.ts');

/** 读取并执行单个篇章 TS 文件（transpile 成 CJS 后取 exports） */
function loadChapterFile(file) {
  const src = fs.readFileSync(file, 'utf8');
  const js = ts.transpileModule(src, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2017 }
  }).outputText;
  const m = { exports: {} };
  new Function('module', 'exports', 'require', js)(m, m.exports, require);
  return m.exports;
}

// 1. 收集全部章句（按 id 排序，保证输出确定性）
const allVerses = [];
for (let i = 1; i <= 20; i++) {
  const file = path.join(VERSES_DIR, `chapter${i}.ts`);
  const mod = loadChapterFile(file);
  const key = `chapter${i}Verses`;
  if (!mod[key]) {
    throw new Error(`生成失败：${file} 缺少导出 ${key}`);
  }
  allVerses.push(...mod[key]);
}
allVerses.sort((a, b) => a.id - b.id);

// 2. 校验基本完整性（与 tests/data.integrity.test.ts 口径一致）
const EXPECTED = 509;
if (allVerses.length !== EXPECTED) {
  throw new Error(`生成失败：章句数 ${allVerses.length} ≠ 预期 ${EXPECTED}，请检查数据`);
}
for (const v of allVerses) {
  if (!v.id || !v.chapterId || !v.original || !v.translation || !v.commentary || !v.keyPoint) {
    throw new Error(`生成失败：章句 id=${v.id} 字段不完整`);
  }
}

// 3. 序列化 + deflateRaw + base64
const payload = JSON.stringify({ verses: allVerses });
const deflated = zlib.deflateRawSync(Buffer.from(payload, 'utf8'), { level: 9 });
const b64 = deflated.toString('base64');

// 4. 写文件（无时间戳，内容不变时输出可复现）
const out = `// AUTO-GENERATED by scripts/compress_verses.cjs —— 请勿手改
// 数据源：src/data/verses/chapter1..20.ts（509 条）；数据变更后运行：npm run data:compress
// 格式：base64( deflateRaw( utf8( JSON.stringify({ verses: Verse[] }) ) ) )
// 运行时解压：src/utils/inflate.ts（inflateRaw + base64ToBytes + utf8Decode）
export const VERSES_BLOB_B64 =
  '${b64}';
`;
fs.writeFileSync(OUT_FILE, out, 'utf8');

// 5. 统计
const srcBytes = Buffer.byteLength(payload, 'utf8');
console.log(`章句数：${allVerses.length}`);
console.log(`源数据：${(srcBytes / 1024).toFixed(0)} KB → deflateRaw：${(deflated.length / 1024).toFixed(0)} KB → base64：${(b64.length / 1024).toFixed(0)} KB`);
console.log(`已写入 ${path.relative(ROOT, OUT_FILE)}`);
