/**
 * 同步英文章句数据（lunyu-web → lunyu-miniapp）→ 压缩 blob
 *
 * 背景：lunyu-web 已完成中英双语改造，英文数据（20 篇章句 + 章节元数据）以 web 为单一源，
 * 由子代理翻译产线产出并经 web 侧 versesEn.test.ts 验收。本脚本将其同步到小程序：
 *   1. 读取 ../lunyu-web/src/data/verses-en/chapter1..20.ts（VerseEn[]）
 *   2. 读取 ../lunyu-web/src/data/chaptersEn.ts（章节英文标题/简介，theme 保留中文关联键）
 *   3. 与中文 versesIndex 逐 id 校验（509 条，无缺漏/多余）
 *   4. 序列化 deflateRaw + base64 → src/data/versesEnData.compressed.ts（分包懒解压，同中文 blob 方案）
 *   5. 生成 src/data/chaptersEn.ts（纯 TS，体量小不压缩）
 *
 * 数据格式：base64( deflateRaw( utf8( JSON.stringify({ versesEn: VerseEn[] }) ) ) )
 * 运行时解压：src/data/versesEnLoader.ts（复用 src/utils/inflate.ts）
 *
 * 与 sync-data.mjs（miniapp → web，中文）方向相反，互不回写、无循环依赖。
 *
 * 运行：node scripts/sync-en-data.mjs（web 侧英文数据更新后执行）
 */
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
// eslint-disable-next-line @typescript-eslint/no-var-requires
const ts = require('typescript');

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const WEB_DATA = path.join(ROOT, '..', 'lunyu-web', 'src', 'data');
const OUT_BLOB = path.join(ROOT, 'src', 'data', 'versesEnData.compressed.ts');
const OUT_CHAPTERS = path.join(ROOT, 'src', 'data', 'chaptersEn.ts');

/** 读取并执行单个 TS 文件（transpile 成 CJS 后取 exports，与 compress_verses.cjs 同法） */
function loadTsModule(file) {
  const src = fs.readFileSync(file, 'utf8');
  const js = ts.transpileModule(src, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2017 }
  }).outputText;
  const m = { exports: {} };
  new Function('module', 'exports', 'require', js)(m, m.exports, require);
  return m.exports;
}

/** 解码 HTML 实体残留（与 web/scripts/sync-data.mjs 口径一致） */
function decodeEntities(code) {
  return code
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&');
}

// 1. 收集英文章句（按 id 排序，保证输出确定性）
const allVersesEn = [];
for (let i = 1; i <= 20; i++) {
  const file = path.join(WEB_DATA, 'verses-en', `chapter${i}.ts`);
  const mod = loadTsModule(file);
  const key = `chapter${i}EnVerses`;
  if (!mod[key]) throw new Error(`同步失败：${file} 缺少导出 ${key}`);
  allVersesEn.push(...mod[key]);
}
allVersesEn.sort((a, b) => a.id - b.id);

// 2. 与中文 id 逐一对齐校验（英文 id 照抄中文源，含历史空洞）
const zhIndex = loadTsModule(path.join(ROOT, 'src', 'data', 'versesIndex.ts')).versesIndex;
const zhIds = new Set(zhIndex.map(v => v.id));
const enIds = new Set(allVersesEn.map(v => v.id));
const missing = [...zhIds].filter(id => !enIds.has(id));
const extra = [...enIds].filter(id => !zhIds.has(id));
if (missing.length || extra.length) {
  throw new Error(`同步失败：中英 id 不对齐 —— 英文缺 ${JSON.stringify(missing)}，英文多 ${JSON.stringify(extra)}`);
}

// 3. 字段完整性（与 compress_verses.cjs 校验口径一致；commentary 保留 web 的 --- 分节结构）
for (const v of allVersesEn) {
  if (!v.id || !v.translation || !v.commentary || !v.keyPoint) {
    throw new Error(`同步失败：英文章句 id=${v.id} 字段不完整`);
  }
}

// 4. deflate + base64 → blob
const payload = JSON.stringify({ versesEn: allVersesEn });
const deflated = zlib.deflateRawSync(Buffer.from(payload, 'utf8'), { level: 9 });
const b64 = deflated.toString('base64');

const blobOut = `// AUTO-GENERATED by scripts/sync-en-data.mjs —— 请勿手改
// 数据源：../lunyu-web/src/data/verses-en/chapter1..20.ts（509 条英文章句）；web 侧更新后运行：node scripts/sync-en-data.mjs
// 格式：base64( deflateRaw( utf8( JSON.stringify({ versesEn: VerseEn[] }) ) ) )
// 运行时解压：src/data/versesEnLoader.ts（复用 src/utils/inflate.ts）
export const VERSES_EN_BLOB_B64 =
  '${b64}';
`;
fs.writeFileSync(OUT_BLOB, blobOut, 'utf8');

// 5. 章节英文元数据：拷贝 web 源码（路径别名相同 ../types，实体解码即可）
const chaptersSrc = decodeEntities(
  fs.readFileSync(path.join(WEB_DATA, 'chaptersEn.ts'), 'utf8')
);
fs.writeFileSync(OUT_CHAPTERS, chaptersSrc, 'utf8');

// 6. 统计
console.log(`英文章句：${allVersesEn.length} 条（与中文 id 完全对齐）`);
console.log(`源数据：${(Buffer.byteLength(payload, 'utf8') / 1024).toFixed(0)} KB → deflateRaw：${(deflated.length / 1024).toFixed(0)} KB → base64：${(b64.length / 1024).toFixed(0)} KB`);
console.log(`已写入 ${path.relative(ROOT, OUT_BLOB)}`);
console.log(`已写入 ${path.relative(ROOT, OUT_CHAPTERS)}`);
